### ISSUE TITLE
Backend Vulnerability - Maliciously change another user's file / put a file at any place of the server

### ISSUE THREAD

**Issue by gty929** [gty929/IMAGician#3]
The vulnerability is due to the following line in index.py
![image](https://user-images.githubusercontent.com/69721857/161227598-bb324b58-5447-477d-bfd3-072a10fa62dc.png)

https://github.com/gty929/IMAGician/blob/e05b71877e8d4b56083fd95932bfa79239d8da59/server/imagician/views/index.py#L291

Since `filename` is uploaded by the user, an attacker can set a filename such as "../../evil.sh", and consequently "evil.sh" will be put in a parent folder on the server. 

The attacker can also include another folder uid (which is accessible via the tag) in the filename,  i.e., "../another_folder_uid/evil.sh." Based on my test result, the server will return "evil.sh" if another user request for the file later.
![image](https://user-images.githubusercontent.com/69721857/161229368-e1e8dc32-5605-43e7-ae46-1314c7035420.png)

Similarly, the `download_file` function also seems vulnerable.
![image](https://user-images.githubusercontent.com/69721857/161229960-4e366cda-123e-44c5-b0df-dd056d5f8766.png)
https://github.com/gty929/IMAGician/blob/e05b71877e8d4b56083fd95932bfa79239d8da59/server/imagician/views/index.py#L226
The attacker will have access to any file on the server, if they can encode `.` and `/` into the `uuid`.

A simple countermeasure would be to ensure that the `filename`s and `uuid`s do not contain special characters such as `.` and `/`, though I'm not sure whether it will prevent all attacks.

**Comment by danielhe2000** [comment]
Thanks. Solved.
